[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "nnfspy"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26.4",
    "matplotlib>=3.8.3",
    "nnfs>=0.5.1",
]
packages = [
    { include = "nnfspy", from = "src" },
]

[project.optional-dependencies]
test = [
    "pytest>=8.1.1",
]
dev = [
    "jupyterlab>=4.1.5",
    "ruff>=0.3.3",
]

[tool.pyright]
extraPaths = ["__pypackages__/3.12/lib/"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F403"]

[tool.pytest.ini_options]
testpaths = ["tests"]
