[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "nnfspy"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = ["numpy", "matplotlib"]

[project.optional-dependencies]
test = ["pytest"]
